load_module /usr/lib/nginx/modules/ngx_http_auth_jwt_module.so;

env JWT_SECRET;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        server hr-helper:8086;
    }

    upstream web-app {
        server web-app:80;
    }

    client_body_timeout 10s;
    client_header_timeout 10s;
    send_timeout 10s;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 1000;
    gzip_types text/plain text/css text/xml application/json application/javascript
               application/xml application/xml+rss text/javascript;

    server {
        listen 80;
        server_name kekly.ru;

        auth_jwt_key "805a686c1f2a27b1510363d035ff296a6f5c109631847ef45cc1d559f32ffd82";
        auth_jwt     off;

        set $jwt_token "";
        if ($http_kek_authorization ~* "^Bearer\s+(.+)$") {
            set $jwt_token $1;
        }
        if ($jwt_token = "") {
            set $jwt_token $cookie_jwt_token;
        }

        # Передаем дальше те IP-заголовки, которые прислал Traefik
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $http_x_real_ip;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;


        location /api/bot {
            proxy_pass http://backend;
        }

        location /api {
            proxy_pass http://backend;
        }

        location  ~ ^/api/[^/]+/(login|auth|logout)$ {
            proxy_pass http://backend;
        }

        location = / {
           return 302 /candidates;
        }

        location / {
           proxy_pass http://web-app;
        }

        location ~ ^/(candidates|vacancies) {
           auth_jwt $jwt_token;
           error_page 401 = @login_redirect;

           proxy_pass http://web-app;
        }

        location @login_redirect {
           return 302 /login;
        }
    }
}
